#!/bin/bash
# refresh_catalog.sh
# Scans the projects directory and updates the catalog
# Usage: ./scripts/refresh_catalog.sh [projects_dir]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CATALOG_DIR="$(dirname "$SCRIPT_DIR")/catalog"
PROJECTS_DIR="${1:-/Users/richardstainforth/Projects}"

echo "=== Project Catalog Refresh ==="
echo "Projects directory: $PROJECTS_DIR"
echo "Catalog directory: $CATALOG_DIR"
echo ""

# Validate projects directory
if [[ ! -d "$PROJECTS_DIR" ]]; then
    echo "Error: Projects directory not found: $PROJECTS_DIR"
    exit 1
fi

# Temporary file for building YAML
TEMP_YAML=$(mktemp)

# Write YAML header
cat > "$TEMP_YAML" << 'YAML_HEADER'
# Project Catalog
# Last updated: DATE_PLACEHOLDER
# Generated by: refresh_catalog.sh

projects:
YAML_HEADER

# Replace date placeholder
sed -i '' "s/DATE_PLACEHOLDER/$(date '+%Y-%m-%d')/" "$TEMP_YAML"

# Function to detect primary language
detect_language() {
    local dir="$1"

    if [[ -f "$dir/tsconfig.json" ]]; then
        echo "TypeScript"
    elif [[ -f "$dir/package.json" ]]; then
        echo "JavaScript"
    elif [[ -f "$dir/pyproject.toml" || -f "$dir/requirements.txt" ]]; then
        echo "Python"
    elif [[ -f "$dir/go.mod" ]]; then
        echo "Go"
    elif find "$dir" -maxdepth 2 -name "*.ps1" 2>/dev/null | head -1 | grep -q .; then
        echo "PowerShell"
    elif find "$dir" -maxdepth 2 -name "*.html" 2>/dev/null | head -1 | grep -q .; then
        echo "HTML/CSS"
    elif find "$dir" -maxdepth 2 -name "*.md" 2>/dev/null | head -1 | grep -q .; then
        echo "Markdown"
    else
        echo "Unknown"
    fi
}

# Function to detect build system
detect_build_system() {
    local dir="$1"

    if [[ -f "$dir/next.config.js" || -f "$dir/next.config.mjs" ]]; then
        echo "Next.js"
    elif [[ -f "$dir/vite.config.ts" || -f "$dir/vite.config.js" ]]; then
        echo "Vite"
    elif [[ -f "$dir/package.json" ]]; then
        echo "npm"
    else
        echo "none"
    fi
}

# Function to detect category from name
detect_category() {
    local name="$1"

    if [[ "$name" == lib-* ]]; then
        echo "libs"
    elif [[ "$name" == personal-* ]]; then
        echo "personal"
    elif [[ "$name" == *-toolbox || "$name" == *-checker || "$name" == *-monitor || "$name" == *-classifier ]]; then
        echo "tools"
    elif [[ "$name" == *-audits ]]; then
        echo "docs"
    else
        echo "apps"
    fi
}

# Function to detect domain from name
detect_domain() {
    local name="$1"

    echo "$name" | sed 's/-.*//'
}

# Function to check README quality
check_readme_quality() {
    local dir="$1"

    if [[ ! -f "$dir/README.md" ]]; then
        echo "missing"
    else
        local lines
        lines=$(wc -l < "$dir/README.md" | tr -d ' ')
        if [[ $lines -gt 50 ]]; then
            echo "good"
        elif [[ $lines -gt 10 ]]; then
            echo "minimal"
        else
            echo "stub"
        fi
    fi
}

# Scan projects
project_count=0
violation_count=0

for dir in "$PROJECTS_DIR"/*/; do
    # Skip non-git directories and the catalog itself
    if [[ ! -d "${dir}.git" ]] || [[ "$(basename "$dir")" == "project-catalog" ]]; then
        continue
    fi

    name=$(basename "$dir")
    cd "$dir"

    # Get git info
    remote=$(git remote get-url origin 2>/dev/null || echo "none")
    last_commit=$(git log -1 --format="%ci" 2>/dev/null | cut -d' ' -f1 || echo "unknown")

    # Check if archived
    if gh repo view "$remote" --json isArchived -q '.isArchived' 2>/dev/null | grep -q true; then
        repo_status="archived"
    else
        repo_status="active"
    fi

    # Detect metadata
    language=$(detect_language "$dir")
    build_system=$(detect_build_system "$dir")
    category=$(detect_category "$name")
    domain=$(detect_domain "$name")
    readme_quality=$(check_readme_quality "$dir")

    # Check scorecard items
    ci_present="false"
    [[ -d "$dir/.github/workflows" ]] && ci_present="true"

    tests_present="false"
    [[ -d "$dir/tests" || -d "$dir/__tests__" || -d "$dir/test" ]] && tests_present="true"

    lint_present="false"
    [[ -f "$dir/.eslintrc.js" || -f "$dir/.eslintrc.cjs" || -f "$dir/eslint.config.js" ]] && lint_present="true"

    security_scan="false"
    [[ -f "$dir/.github/workflows/security-scan.yml" ]] && security_scan="true"

    # Write project entry
    cat >> "$TEMP_YAML" << YAML_ENTRY
  - name: $name
    display_name: $(echo "$name" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')
    path: ${dir%/}
    category: $category
    domain: $domain
    description: ""
    language: $language
    build_system: $build_system
    remote: $remote
    status: $repo_status
    last_commit: "$last_commit"
    scorecard:
      ci_present: $ci_present
      tests_present: $tests_present
      lint_present: $lint_present
      readme_quality: $readme_quality
      security_scan: $security_scan

YAML_ENTRY

    ((project_count++))

    # Check naming convention
    if ! echo "$name" | grep -qE '^[a-z0-9]+(-[a-z0-9]+)*$'; then
        echo "⚠️  Naming violation: $name"
        ((violation_count++))
    fi

    cd "$PROJECTS_DIR"
done

# Move temp file to catalog
mv "$TEMP_YAML" "$CATALOG_DIR/projects.yaml"

echo ""
echo "=== Summary ==="
echo "Projects scanned: $project_count"
echo "Naming violations: $violation_count"
echo ""
echo "Catalog updated: $CATALOG_DIR/projects.yaml"
echo ""
echo "Next steps:"
echo "  1. Review the YAML and add descriptions"
echo "  2. Regenerate projects.md if needed"
echo "  3. Commit and push the updated catalog"
